import { Resend } from 'resend'
import { NextResponse } from 'next/server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  try {
    const { email, totalSpend, potentialSavings } = await request.json()

    // First, verify your email in Resend dashboard -> Audience -> Add email
    // For testing, you can only send to your own verified email
    
    const { data, error } = await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: [email],  // Must be a verified email in Resend
      subject: 'Your AI Spend Audit Report',
      html: `
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"></head>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
          <h1 style="color: #2563eb;">AI Spend Audit Results</h1>
          <p><strong>Total Monthly Spend:</strong> $${totalSpend}</p>
          <p><strong>Potential Savings:</strong> $${potentialSavings}</p>
          <p style="margin-top: 20px;">${potentialSavings > 100 ? '🎉 You qualify for a free consultation with Credex.' : '✅ Your spending is already well optimized!'}</p>
          <hr />
          <p style="color: #6b7280; font-size: 12px;">Generated by Credex AI Spend Auditor</p>
        </body>
        </html>
      `
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, data })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }
}