import { Resend } from 'resend'
import { NextResponse } from 'next/server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  try {
    const { email, totalSpend, potentialSavings } = await request.json()

    const { data, error } = await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: [email],
      subject: 'Your AI Spend Audit Report',
      html: `
        <h1>AI Spend Audit Results</h1>
        <p><strong>Total Monthly Spend:</strong> $${totalSpend}</p>
        <p><strong>Potential Savings:</strong> $${potentialSavings}</p>
        <p>${potentialSavings > 100 ? 'You qualify for a free consultation with Credex.' : 'Your spending is well optimized!'}</p>
        <hr />
        <p>Generated by Credex AI Spend Auditor</p>
      `
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error }, { status: 500 })
    }

    return NextResponse.json({ success: true, data })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }
}