'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'

export default function SharedAuditPage() {
  const params = useParams()
  const id = params.id
  const [data, setData] = useState<any>(null)
  const [notFound, setNotFound] = useState(false)

  useEffect(() => {
    if (!id) return
    
    async function loadAudit() {
      try {
        const res = await fetch(`/api/audit/${id}`)
        if (!res.ok) throw new Error('Not found')
        const audit = await res.json()
        setData(audit)
      } catch (error) {
        setNotFound(true)
      }
    }
    loadAudit()
  }, [id])

  if (notFound) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-2xl font-bold mb-4">Audit Not Found</h1>
          <p className="text-gray-600">This audit link is invalid or has expired.</p>
        </div>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12">
        <div className="container mx-auto px-4 text-center">
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white rounded-lg shadow-xl p-8">
          <h1 className="text-2xl font-bold mb-6">Shared Audit Results</h1>
          
          <div className="grid grid-cols-2 gap-6 mb-8">
            <div className="bg-blue-50 p-6 rounded-lg">
              <p className="text-sm text-blue-600 font-semibold">Total Monthly Spend</p>
              <p className="text-3xl font-bold text-blue-900">${data.totalSpend}</p>
            </div>
            <div className="bg-green-50 p-6 rounded-lg">
              <p className="text-sm text-green-600 font-semibold">Potential Savings</p>
              <p className="text-3xl font-bold text-green-600">${data.potentialSavings}</p>
            </div>
          </div>

          <div className="overflow-x-auto mb-8">
            <table className="min-w-full bg-white border border-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500">Tool</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500">Recommendation</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500">Savings</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {data.results.map((result: any, index: number) => (
                  <tr key={index} className="hover:bg-gray-50">
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">{result.toolName}</td>
                    <td className="px-6 py-4 text-sm text-gray-500">{result.recommendation}</td>
                    <td className="px-6 py-4 text-sm font-semibold text-green-600">${result.potentialSavings}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="text-center text-gray-500 text-sm">
            <p>Generated by Credex AI Spend Auditor</p>
          </div>
        </div>
      </div>
    </div>
  )
}